### ISSUE TITLE
111111 입력시 십일만천백열한개가 아닌 십만천백열한개로 출력됩니다.

### ISSUE THREAD

**Issue by uuidcode** [crucifyer/koreanCardinalOrdinal#1]
111111 입력시 십일만천백열한개가 아닌 십만천백열한개로 출력됩니다.

**Comment by crucifyer** [comment]
일 생략을 만단위에서 제외했습니다.

**Comment by uuidcode** [comment]
11111 입력시 만천백열한개가 아닌 일만천백열한개로 출력됩니다.
이 부분도 한번 봐주시면 고맙겠습니다.

**Comment by crucifyer** [comment]
아하, 첫 만단위를 고려하게 수정했습니다.
